spring.application.name=student-management-system

logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Swagger Configuration
springdoc.swagger-ui.use-root-path=true
springdoc.api-docs.server-url=/

# Database Configuration
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console