spring.application.name=student-management-system

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true